version: "3.1"

services:
  db:
    image: postgres
    container_name: django-2-sql-db-1
    restart: always
    environment:
      POSTGRES_DB: djangotraining
      POSTGRES_USER: djangouser
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: django-2-sql-adminer-1
    restart: always
    ports:
      - "8080:8080"

volumes:
  db-data:


